// Central registry: maps every navigation slug to its Supabase table and the
// exact columns from the reference Zoho Creator app (field-for-field).

export type ReportColumn = { key: string; label: string; numeric?: boolean };

export type ReportDef = {
  slug: string;
  label: string;
  table: string;
  columns: ReportColumn[];
};

const num = (label: string, key: string): ReportColumn => ({ key, label, numeric: true });
const txt = (label: string, key: string): ReportColumn => ({ key, label });

export const REPORTS: ReportDef[] = [
  {
    slug: "diesel-entries",
    label: "Diesel Entries",
    table: "diesel_entries",
    columns: [
      txt("ID", "zoho_id"),
      txt("Source", "source"),
      txt("Date", "entry_date"),
      txt("Driver", "driver"),
      txt("Vehicle", "vehicle"),
      num("Diesel Liters", "diesel_liters"),
      num("Diesel Rate Per Liter", "diesel_rate_per_liter"),
      num("Diesel Amount", "diesel_amount"),
      txt("Mileage", "mileage"),
      txt("Tank Status", "tank_status"),
      txt("Rec From", "rec_from"),
      num("From KM", "from_km"),
      num("To KM", "to_km"),
      num("Total KM", "total_km"),
      txt("DC Number", "dc_number"),
      txt("Added User", "added_user"),
      txt("Added Time", "added_time"),
    ],
  },
  {
    slug: "def-oil-entries",
    label: "Def Oil Entries",
    table: "def_oil_entries",
    columns: [
      txt("ID", "zoho_id"),
      txt("Date-Time", "date_time"),
      txt("Transporters", "transporters"),
      txt("Vehicle", "vehicle"),
      txt("Driver", "driver"),
      txt("Source", "source"),
      num("Def Oil Per Liter", "def_oil_per_liter"),
      num("Def Oil Liters", "def_oil_liters"),
      num("Def Oil Amount", "def_oil_amount"),
      txt("Rec From", "rec_from"),
      txt("Mileage", "mileage"),
      num("From KM", "from_km"),
      num("To KM", "to_km"),
      num("Total KM", "total_km"),
      txt("Bunk Reference", "bunk_reference"),
      txt("Tank Status", "tank_status"),
    ],
  },
  {
    slug: "sales-entries",
    label: "Sales Entries",
    table: "sales_entries",
    columns: [
      txt("Sales ID", "sales_id"),
      txt("DC No", "dc_no"),
      txt("Date", "entry_date"),
      txt("Transporters", "transporters"),
      txt("Purchase From", "purchase_from"),
      txt("Client Name", "client_name"),
      txt("Delivery Location", "delivery_location"),
      txt("Vehicle", "vehicle"),
      txt("Driver", "driver"),
      num("Purchase Quantity", "purchase_quantity"),
      txt("Materials", "materials"),
      txt("Purchase Unit", "purchase_unit"),
      num("Purchase Net Total", "purchase_net_total"),
      num("Sales Quantity", "sales_quantity"),
      txt("Sales Unit", "sales_unit"),
      num("Sales Net Total", "sales_net_total"),
      num("Driver Padi", "driver_padi"),
      num("Driver Food Amount", "driver_food_amount"),
      num("Shed Work Amount", "shed_work_amount"),
      num("Total Vehicle Expense", "total_vehicle_expense"),
      num("Driver Advance", "driver_advance"),
      num("Driver Net Total", "driver_net_total"),
      num("Diesel Amount", "diesel_amount"),
      num("Profit", "profit"),
    ],
  },
  {
    slug: "rent-entries",
    label: "Rent Entries",
    table: "rent_entries",
    columns: [
      txt("Rent Entry ID", "rent_entry_id"),
      txt("Date", "entry_date"),
      txt("DC No", "dc_no"),
      txt("Transporters", "transporters"),
      txt("Purchase From", "purchase_from"),
      txt("Material", "material"),
      num("Quantity", "quantity"),
      txt("Unit", "unit"),
      txt("Client Name", "client_name"),
      txt("Delivery Location", "delivery_location"),
      num("Rent Quantity", "rent_quantity"),
      num("Rent Price (Per Unit/Ton)", "rent_price"),
      num("Rent Amount", "rent_amount"),
      num("Rent Amount with GST", "rent_amount_with_gst"),
      txt("Vehicle Number", "vehicle_number"),
      txt("Driver Name", "driver_name"),
      num("Driver Padi", "driver_padi"),
      num("Driver Food Amount", "driver_food_amount"),
      num("Shed Work Amount", "shed_work_amount"),
      num("Total Vehicle Expense", "total_vehicle_expense"),
      num("Driver Advance", "driver_advance"),
      num("Driver Net Total", "driver_net_total"),
      txt("Diesel Source", "diesel_source"),
      num("Diesel Liters", "diesel_liters"),
      num("From KM", "from_km"),
      num("To KM", "to_km"),
      num("Total KM", "total_km"),
      txt("Mileage", "mileage"),
      txt("Tank Status", "tank_status"),
      txt("Bunk Reference", "bunk_reference"),
      num("Diesel Rate Per Liter", "diesel_rate_per_liter"),
      num("Diesel Amount", "diesel_amount"),
      num("Total Trip Expense", "total_trip_expense"),
      num("Profit", "profit"),
      txt("ID", "zoho_id"),
      txt("Modified User", "modified_user"),
    ],
  },
  {
    slug: "day-fees-entries",
    label: "Day Fees Entries",
    table: "day_fees_entries",
    columns: [
      txt("ID", "zoho_id"),
      txt("DC Number", "dc_number"),
      txt("Date", "entry_date"),
      txt("Purchase From", "purchase_from"),
      txt("Client Name", "client_name"),
      txt("Delivery Location", "delivery_location"),
      txt("Material", "material"),
      txt("Unit", "unit"),
      num("Quantity", "quantity"),
      num("Total load", "total_load"),
      txt("Vehicle Number", "vehicle_number"),
      txt("Driver Name", "driver_name"),
      num("Per Day amount", "per_day_amount"),
      num("Amount with GST", "amount_with_gst"),
      num("Driver Padi", "driver_padi"),
      num("Driver Food Amount", "driver_food_amount"),
      num("Shed Work Amount", "shed_work_amount"),
      num("Driver Advance", "driver_advance"),
      num("Driver Net Total", "driver_net_total"),
      txt("Diesel Source", "diesel_source"),
      num("Diesel Liters", "diesel_liters"),
      num("Diesel Amount", "diesel_amount"),
      txt("Bunk Reference", "bunk_reference"),
      num("Total Vehicle Expense", "total_vehicle_expense"),
      num("Total Trip Expense", "total_trip_expense"),
      num("Profit", "profit"),
    ],
  },
  {
    slug: "all-boulders-entries",
    label: "All Boulders Entries",
    table: "boulder_entries",
    columns: [
      txt("ID", "zoho_id"),
      txt("Date", "entry_date"),
      txt("Boulder Shift", "boulder_shift"),
      txt("Business Transporters", "business_transporters"),
      txt("Client Name", "client_name"),
      txt("Unit", "unit"),
      txt("Boulders Source", "boulders_source"),
      num("Total Loads", "total_loads"),
      num("Total Tons", "total_tons"),
      num("Ton Per Rate", "ton_per_rate"),
      num("Amount", "amount"),
      num("GST", "gst"),
      num("GST Amount", "gst_amount"),
      num("Amount with GST", "amount_with_gst"),
      txt("Vehicle Number", "vehicle_number"),
      txt("Driver Name", "driver_name"),
      num("Driver Padi", "driver_padi"),
      num("Driver Food Amount", "driver_food_amount"),
      num("Driver Advance", "driver_advance"),
      txt("Choose Account", "choose_account"),
      num("Driver Net Total", "driver_net_total"),
      num("Total Vehicle Expense", "total_vehicle_expense"),
      txt("Diesel Source", "diesel_source"),
      num("Diesel Liters", "diesel_liters"),
      num("Diesel Amount", "diesel_amount"),
      txt("Bunk Reference", "bunk_reference"),
      num("Total Trip Expense", "total_trip_expense"),
      num("Profit", "profit"),
    ],
  },
  {
    slug: "boulders-diesel-entries",
    label: "Boulders Diesel Entries",
    table: "boulder_diesel_entries",
    columns: [
      txt("ID", "zoho_id"),
      txt("Source", "source"),
      txt("Date", "entry_date"),
      txt("Vehicle", "vehicle"),
      txt("Driver", "driver"),
      num("Diesel Rate Per Liter", "diesel_rate_per_liter"),
      num("Diesel Liters", "diesel_liters"),
      txt("Mileage", "mileage"),
      num("Diesel Amount", "diesel_amount"),
      txt("Bunk Reference", "bunk_reference"),
      txt("Tank Status", "tank_status"),
      txt("Rec From", "rec_from"),
      txt("Boulders Entries", "boulders_entries"),
      txt("DC Number", "dc_number"),
      txt("Added User", "added_user"),
    ],
  },
  {
    slug: "excavators-entries",
    label: "Excavators Entries",
    table: "excavator_entries",
    columns: [
      txt("ID", "zoho_id"),
      txt("Date", "entry_date"),
      txt("Excavator", "excavator"),
      txt("Shift", "shift"),
      txt("Client", "client"),
      txt("Vehicle", "vehicle"),
      txt("Material", "material"),
      num("Loads", "loads"),
      num("Tons", "tons"),
      num("Rate", "rate"),
      num("Amount", "amount"),
    ],
  },
  {
    slug: "excavators-daily-entries",
    label: "Excavators Daily Entries",
    table: "excavator_daily_entries",
    columns: [
      txt("ID", "zoho_id"),
      txt("Date", "entry_date"),
      txt("Client", "client"),
      num("Loads /Day", "loads_per_day"),
      num("Ton / Day", "ton_per_day"),
      num("Ton Per Rate", "ton_per_rate"),
      num("Amount", "amount"),
      num("GST", "gst"),
      num("Gst Amount", "gst_amount"),
      num("Amount With GST", "amount_with_gst"),
      txt("Diesel Source", "diesel_source"),
      txt("Bunk Reference", "bunk_reference"),
      num("Diesel Liters", "diesel_liters"),
      num("Diesel Rate", "diesel_rate"),
      num("Diesel Amount", "diesel_amount"),
      num("Profit", "profit"),
      txt("Added Time", "added_time"),
    ],
  },
  {
    slug: "excavators-rent-entries",
    label: "Excavators Rent Entries",
    table: "excavator_rent_entries",
    columns: [
      txt("Rent ID", "rent_id"),
      txt("Date", "entry_date"),
      txt("Machine", "machine"),
      txt("Driver", "driver"),
      txt("Client", "client"),
      num("Start Hour", "start_hour"),
      num("End Hour", "end_hour"),
      num("Total Hour", "total_hour"),
      num("Rate Per Hour", "rate_per_hour"),
      num("Amount", "amount"),
      num("GST", "gst"),
      num("Gst Amount", "gst_amount"),
      num("Amount With GST", "amount_with_gst"),
      txt("Diesel Source", "diesel_source"),
      num("Diesel Filling (L)", "diesel_filling_l"),
      num("Diesel Rate Per Liter", "diesel_rate_per_liter"),
      num("Diesel Amount", "diesel_amount"),
      txt("Tank Status", "tank_status"),
      txt("Bunk Reference", "bunk_reference"),
      txt("Mileage", "mileage"),
      txt("Remarks", "remarks"),
    ],
  },
  {
    slug: "excavators-diesel-entries",
    label: "Excavators Diesel Entries",
    table: "excavator_diesel_entries",
    columns: [
      txt("ID", "zoho_id"),
      txt("Date", "entry_date"),
      txt("Source", "source"),
      txt("Machine", "machine"),
      txt("Driver", "driver"),
      num("Diesel Liters", "diesel_liters"),
      num("Diesel Rate Per Liter", "diesel_rate_per_liter"),
      num("Diesel Amount", "diesel_amount"),
      txt("Mileage", "mileage"),
      txt("Tank Status", "tank_status"),
      txt("Rec From", "rec_from"),
      txt("Bunk Reference", "bunk_reference"),
      txt("Added User", "added_user"),
      txt("DC Number", "dc_number"),
      txt("Excavators Rent Entries", "excavator_rent_entry_id"),
      txt("Excavators", "excavator_id"),
      txt("Excavators Daily Entries", "excavator_daily_entry_id"),
    ],
  },
  {
    slug: "income-expense",
    label: "Income & Expense",
    table: "income_expense_entries",
    columns: [
      txt("Payment ID", "payment_id"),
      txt("Type", "type"),
      txt("Date-Time", "date_time"),
      txt("Account", "account"),
      txt("Payment For", "payment_for"),
      txt("Category", "category"),
      txt("Remarks", "remarks"),
      num("Income", "income"),
      num("Expense", "expense"),
    ],
  },
  {
    slug: "accounts-overview",
    label: "Accounts",
    table: "accounts",
    columns: [
      txt("Date", "entry_date"),
      txt("Account Type", "account_type"),
      txt("Bank Name", "bank_name"),
      txt("Display Name", "display_name"),
      txt("Holder", "holder"),
      num("Cash Adjustment", "cash_adjustment"),
      num("Money Transfer", "money_transfer"),
      num("Current Balance", "current_balance"),
    ],
  },
  {
    slug: "drivers",
    label: "Drivers",
    table: "drivers",
    columns: [
      txt("Driver ID", "driver_id"),
      txt("Driver Name", "driver_name"),
      txt("Driver Image", "driver_image"),
      txt("Phone", "phone"),
      txt("License Number", "license_number"),
      num("Opening Balance", "opening_balance"),
      num("Old Balance", "old_balance"),
      num("Driver Balance", "driver_balance"),
      num("Total Driver Balance", "total_driver_balance"),
    ],
  },
  {
    slug: "clients",
    label: "Clients",
    table: "clients",
    columns: [
      txt("Client ID", "client_id"),
      txt("Added Time", "added_time"),
      txt("Client Name", "client_name"),
      txt("Address", "address"),
      txt("Email", "email"),
      txt("Phone", "phone"),
      txt("GSTIN", "gstin"),
      num("Opening Balance", "opening_balance"),
      num("Old Balance", "old_balance"),
      num("Current Balance", "current_balance"),
      num("Diesel Balance", "diesel_balance"),
      num("Total Client Balance", "total_client_balance"),
    ],
  },
  {
    slug: "vendors",
    label: "Vendors",
    table: "vendors",
    columns: [
      txt("Vendor ID", "vendor_id"),
      txt("Added Time", "added_time"),
      txt("Vendor Name", "vendor_name"),
      txt("Phone", "phone"),
      txt("Email", "email"),
      txt("GSTIN", "gstin"),
      txt("Address", "address"),
      num("Opening Balance", "opening_balance"),
      num("Old Balance", "old_balance"),
      num("Current Balance", "current_balance"),
      num("Total Vendor Balance", "total_vendor_balance"),
    ],
  },
  {
    slug: "vehicles",
    label: "Vehicles",
    table: "fleet_vehicles",
    columns: [
      txt("Vehicle ID", "vehicle_id"),
      txt("Vehicle Name", "vehicle_name"),
      txt("ID", "zoho_id"),
      txt("Vehicle Number", "vehicle_number"),
      txt("Vehicle Category", "vehicle_category"),
      txt("Engine Number", "engine_number"),
      txt("Chassis Number", "chassis_number"),
      txt("Insurance Expiry Date", "insurance_expiry_date"),
      txt("FC Valid Till", "fc_valid_till"),
      txt("PUC Valid Till", "puc_valid_till"),
      txt("Road Tax Expiry", "road_tax_expiry"),
    ],
  },
  {
    slug: "material-rates",
    label: "Material Rates",
    table: "material_rates",
    columns: [
      txt("Vendor Name", "vendor_name"),
      txt("Material", "material"),
      txt("Unit", "unit"),
      num("Rate", "rate"),
    ],
  },
  {
    slug: "materials",
    label: "Materials",
    table: "materials",
    columns: [
      txt("Material ID", "material_id"),
      txt("Material Name", "material_name"),
      txt("Material Category", "material_category"),
      txt("Material Unit", "material_unit"),
      txt("Description", "description"),
      txt("Default Sale Rate", "default_sale_rate"),
    ],
  },
  {
    slug: "machines",
    label: "Machines",
    table: "machines",
    columns: [
      txt("Machine ID", "machine_id"),
      txt("Machine Name", "machine_name"),
      txt("Machine Number", "machine_number"),
      txt("Machine Category", "machine_category"),
    ],
  },
  {
    slug: "transporters",
    label: "Transporters",
    table: "transporters",
    columns: [
      txt("Transporters ID", "transporter_id"),
      txt("Transporters Name", "transporter_name"),
      txt("Contact Person", "contact_person"),
      txt("Phone", "phone"),
      txt("Email", "email"),
      num("Transporters Balance", "transporter_balance"),
      txt("Portal Status", "portal_status"),
      txt("Status", "is_active"),
    ],
  },
  {
    slug: "sub-categories",
    label: "Sub Categories",
    table: "sub_categories",
    columns: [txt("Sub Category Name", "sub_category_name")],
  },
  {
    slug: "categories",
    label: "Categories",
    table: "categories",
    columns: [txt("Category Name", "category_name")],
  },
  {
    slug: "units",
    label: "Units",
    table: "units",
    columns: [
      txt("Unit Name", "unit_name"),
      txt("Short Name", "short_name"),
      txt("ID", "zoho_id"),
    ],
  },
  {
    slug: "payment-categories",
    label: "Payment Categories",
    table: "payment_categories",
    columns: [txt("Category Name", "category_name")],
  },
  {
    slug: "company-profile",
    label: "Company Profile",
    table: "company_profile",
    columns: [
      txt("Company Name", "company_name"),
      txt("Contact Person", "contact_person"),
      txt("Email", "email"),
      txt("Phone", "phone"),
      txt("Address", "address"),
    ],
  },
];

export const REPORT_BY_SLUG = new Map(REPORTS.map((r) => [r.slug, r]));

export function findReport(slug: string): ReportDef | undefined {
  return REPORT_BY_SLUG.get(slug);
}