/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAllReportsRouteImport } from './routes/_authenticated/all-reports'
import { Route as AuthenticatedTyreRouteImport } from './routes/_authenticated/tyre'
import { Route as AuthenticatedTyreModuleRouteImport } from './routes/_authenticated/tyre-module'
import { Route as AuthenticatedTyreReportRouteImport } from './routes/_authenticated/tyre-report'
import { Route as AuthenticatedPSplatRouteImport } from './routes/_authenticated/p/$'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAllReportsRoute = AuthenticatedAllReportsRouteImport.update({
  id: '/all-reports',
  path: '/all-reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTyreRoute = AuthenticatedTyreRouteImport.update({
  id: '/tyre',
  path: '/tyre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTyreModuleRoute = AuthenticatedTyreModuleRouteImport.update({
  id: '/tyre-module',
  path: '/tyre-module',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTyreReportRoute = AuthenticatedTyreReportRouteImport.update({
  id: '/tyre-report',
  path: '/tyre-report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPSplatRoute = AuthenticatedPSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/all-reports': typeof AuthenticatedAllReportsRoute
  '/tyre': typeof AuthenticatedTyreRoute
  '/tyre-module': typeof AuthenticatedTyreModuleRoute
  '/tyre-report': typeof AuthenticatedTyreReportRoute
  '/p/$': typeof AuthenticatedPSplatRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/all-reports': typeof AuthenticatedAllReportsRoute
  '/tyre': typeof AuthenticatedTyreRoute
  '/tyre-module': typeof AuthenticatedTyreModuleRoute
  '/tyre-report': typeof AuthenticatedTyreReportRoute
  '/': typeof AuthenticatedIndexRoute
  '/p/$': typeof AuthenticatedPSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/all-reports': typeof AuthenticatedAllReportsRoute
  '/_authenticated/tyre': typeof AuthenticatedTyreRoute
  '/_authenticated/tyre-module': typeof AuthenticatedTyreModuleRoute
  '/_authenticated/tyre-report': typeof AuthenticatedTyreReportRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/p/$': typeof AuthenticatedPSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/all-reports'
    | '/tyre'
    | '/tyre-module'
    | '/tyre-report'
    | '/p/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/all-reports'
    | '/tyre'
    | '/tyre-module'
    | '/tyre-report'
    | '/'
    | '/p/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/all-reports'
    | '/_authenticated/tyre'
    | '/_authenticated/tyre-module'
    | '/_authenticated/tyre-report'
    | '/_authenticated/'
    | '/_authenticated/p/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/all-reports': {
      id: '/_authenticated/all-reports'
      path: '/all-reports'
      fullPath: '/all-reports'
      preLoaderRoute: typeof AuthenticatedAllReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tyre': {
      id: '/_authenticated/tyre'
      path: '/tyre'
      fullPath: '/tyre'
      preLoaderRoute: typeof AuthenticatedTyreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tyre-module': {
      id: '/_authenticated/tyre-module'
      path: '/tyre-module'
      fullPath: '/tyre-module'
      preLoaderRoute: typeof AuthenticatedTyreModuleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tyre-report': {
      id: '/_authenticated/tyre-report'
      path: '/tyre-report'
      fullPath: '/tyre-report'
      preLoaderRoute: typeof AuthenticatedTyreReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$': {
      id: '/_authenticated/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof AuthenticatedPSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAllReportsRoute: typeof AuthenticatedAllReportsRoute
  AuthenticatedTyreRoute: typeof AuthenticatedTyreRoute
  AuthenticatedTyreModuleRoute: typeof AuthenticatedTyreModuleRoute
  AuthenticatedTyreReportRoute: typeof AuthenticatedTyreReportRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPSplatRoute: typeof AuthenticatedPSplatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAllReportsRoute: AuthenticatedAllReportsRoute,
  AuthenticatedTyreRoute: AuthenticatedTyreRoute,
  AuthenticatedTyreModuleRoute: AuthenticatedTyreModuleRoute,
  AuthenticatedTyreReportRoute: AuthenticatedTyreReportRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPSplatRoute: AuthenticatedPSplatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
